[features]
seeds = false
skip-lint = false
[programs.devnet]
epicdemo = "FACJtb84d9qiR8uLqsV51zoo3vYAYJzupanPC3pWDPkC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/grantferowich/.config/solana/id.json"

[scripts]
test = "node tests/epicdemo.js"
